MERGE INTO USER_ROLE KEY (ID) VALUES ( 1 , 'USER' );
MERGE INTO USER_ROLE KEY (ID) VALUES ( 2 , 'ADMIN' );
MERGE INTO USER_ENTITY KEY (ID)
    VALUES ( 1 , 'admin@op.pl','admin','$2a$10$4NyKuhEo7qts5YHeyshf2OJ5XsMgffLPAO4FZM7rlNovuoRpXhWaO','admin','ADMIN');
MERGE INTO USER_ENTITY_ROLES KEY (ROLES_ID, USER_ENTITY_ID) VALUES ('1','2');